services:
  # Laravel-приложение
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: baltpoint-app
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - baltpoint
    depends_on:
      - db

  # Веб-сервер Nginx
  nginx:
    image: nginx:alpine
    container_name: baltpoint-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - baltpoint
    depends_on:
      - app

  # База данных MySQL
  db:
    image: mysql:8.0
    container_name: baltpoint-db
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - baltpoint-dbdata:/var/lib/mysql
    networks:
      - baltpoint

networks:
  baltpoint:
    driver: bridge

volumes:
  baltpoint-dbdata:
    driver: local
